/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AppStateContext: typeof import('./hooks/useAppState').AppStateContext
  const AuthProvider: typeof import('./hooks/useAuth').AuthProvider
  const DataStoreProvider: typeof import('./hooks/useDataStore').DataStoreProvider
  const Fragment: typeof import('react').Fragment
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SetupProvider: typeof import('./hooks/useSetupContext').SetupProvider
  const Sidebar: typeof import('./components/Sidebar').default
  const Suspense: typeof import('react').Suspense
  const ThemeProvider: typeof import('./hooks/useTheme').ThemeProvider
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./lib/utils').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const fuzzyMatch: typeof import('./lib/fuzzySearch').fuzzyMatch
  const fuzzyScore: typeof import('./lib/fuzzySearch').fuzzyScore
  const fuzzySearch: typeof import('./lib/fuzzySearch').fuzzySearch
  const generateId: typeof import('./hooks/useDataStore').generateId
  const getAcademicContext: typeof import('./hooks/useSetupContext').getAcademicContext
  const getMatchHighlights: typeof import('./lib/fuzzySearch').getMatchHighlights
  const isSetupFinished: typeof import('./hooks/useSetupContext').isSetupFinished
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAppState: typeof import('./hooks/useAppState').useAppState
  const useAuth: typeof import('./hooks/useAuth').default
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDataStore: typeof import('./hooks/useDataStore').useDataStore
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useSetup: typeof import('./hooks/useSetupContext').useSetup
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTheme: typeof import('./hooks/useTheme').useTheme
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AppState } from './hooks/useAppState'
  import('./hooks/useAppState')
  // @ts-ignore
  export type { Course, Teacher, Room, Session, WeekSchedule } from './hooks/useDataStore'
  import('./hooks/useDataStore')
}
