spring.application.name=EDT
spring.datasource.url=jdbc:postgresql://localhost:5432/emploi_du_temps
spring.datasource.username=postgres
spring.datasource.password=00000000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=dev
app.jwt.secret=mYs3cR3tK3yF0rEdTPr0j3ct2026ESP_Maurit4nia_P0lyt3chniqu3!!
app.jwt.expMinutes=120

server.port=8080

# To re-seed data manually, run: PGPASSWORD=00000000 psql -U postgres -h localhost -d emploi_du_temps -f src/main/resources/data.sql
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
